### ISSUE TITLE
Failed to use the example

### ISSUE THREAD

**Issue by Majanto** [polymonster/premake-android-studio#23]
Hello!
I'm trying to use this Premake module to build an Android Studio project, but I can't figure out how to use the given example. When I run the generation command, I get a project that seems badly configured:
![image](https://github.com/polymonster/premake-android-studio/assets/35608534/f98ec4d0-c3dd-46ab-993b-1a8a7f569c83)

I'm on Windows
Any idea of what could be my issue here?

Thanks in advance!

**Comment by polymonster** [comment]
Not sure what the issue is, I can try taking a look to see if I can reproduce.

What gradle version are you using?

Changes in this pull request: https://github.com/polymonster/premake-android-studio/pull/21 might help, I can try them and get them merged if it fixes the issue.

**Comment by polymonster** [comment]
I was able to reproduce on latest android studio / windows. Mostly I have been using this on macOS so haven't tested windows for a while.

If you delete the gradle properties file it should get around the issue. The file in the example doesn't have anything in it, but its a stub there for properties which can be specified via premake.

**Comment by polymonster** [comment]
I made a branch in which I am able to build the windows version: https://github.com/polymonster/premake-android-studio/tree/upgrade-gradle

Having trouble getting the gradle version correctly configured now on the CI (linux) so not able to merge to main just yet

**Comment by polymonster** [comment]
Changes are now merged into main,  updated to gradle 8+ and fixed the issue with empty gradle.wrapper files

**Comment by Majanto** [comment]
Sorry for the very late answer 😅
I didn't dig that much, but I remember trying with your changes and having another issue.
I won't look into it soon, so I'm closing this issue for now.
